### ISSUE TITLE
Is there any way to covert the hdf5 file to the KITTI dataset file format for training 

### ISSUE THREAD

**Issue by SaMeEr9597** [eduardohenriquearnold/CODD#1]
Good morning, 
First of all I would like to thank the team for creating this Wonderfull tool for generating multi-agent dataset. I am currently facing an issue on converting the hdf5 file format to KITTI dataset file format for training, it would be great if you could guide me regarding the same,
Thanks

**Comment by eduardohenriquearnold** [comment]
Thanks, I hope the dataset is useful in your research!
Assuming you are talking about the 3D object detection task and that you are extracting 'single-agent' data, i.e. you only use data from one vehicle at a time, there are a few steps to convert the dataset to the KITTI format:

1. Convert each local point cloud from the UE coordinate system (x-forward, y-right, z-up) to the KITTI lidar coordinate system (x-forward, y-left, z-up).
2. Save each point cloud as a binary file (following KITTI's format). To do this, you may use [numpy.ndarray.tofile](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.tofile.html#numpy.ndarray.tofile), using the [N, 4] point cloud as the argument. This should give you the same KITTI point cloud format (see how to read from these files [here](https://github.com/hunse/kitti/blob/master/kitti/velodyne.py#L13))
3. Transform the 3D object labels (provided in the hdf5 datasets `vehicle_boundingbox` and `pedestrian_boundingbox` ) from the global coordinate system (UE4) to the lidar coordinate system (using the inverse sensor pose transform).
4. Store these in the data format provided [here](https://github.com/bostondiditeam/kitti/blob/master/resources/devkit_object/readme.txt#L31).
5. Note that CODD does not provide a camera sensor and that KITTI object labels are represented w.r.t. the camera sensor. So you can assume that the lidar coordinate system is the camera coordinate system (but you will have to adjust for that in the camera-lidar calibration file, which should become the identity transformation).

All in all, I think it'd be easier to write a custom data loader for this dataset rather than converting the dataset to KITTI's format.
As an example of a dataloader for this dataset for the task of point cloud registration, please see https://github.com/eduardohenriquearnold/fastreg/blob/master/lib/dataset/codd.py

**Comment by eduardohenriquearnold** [comment]
I'll close this issue for now. If there are more questions please feel free to reopen.

**Comment by SaMeEr9597** [comment]
Thanks for the detailed explanation, is it possible to explain a bit more about the step 3, which is converting from U4 world coordinate system to KITTI LIDAR coordinate. Or maybe I got your explanation wrong, do you mean that I need to convert from global coordinate system to local coordinate system, if yes, should I still change the Y direction again similar to step 2. Also, can I keep everything in global coordinate system instead.
Thanks for the clarification

**Comment by susanbao** [comment]
@SaMeEr9597 Hi, I am also trying to convert CODD to KITTI dataset format. What is your current process? Maybe we could discuss and cooperate.
